import { Card } from '../interfaces/card';

export const CardsData: Card[] = [
  {
    id: 0,
    name: 'Startpagina',
    speech: 'Startpagina',
    src: '',
    parentId: null,
    childrenIds: [50, 4, 5, 6, 8, 9],
  },
  {
    id: 1,
    name: 'Woonkamer',
    speech: 'Woonkamer',
    src: './images/woonkamer.jpg',
    parentId: 15,
    childrenIds: [15],
    // linkIds: [9],
  },
  {
    id: 2,
    name: 'Keuken',
    speech: 'Keuken',
    src: './images/keuken.jpg',
    parentId: 15,
    childrenIds: [10, 11, 12],
  },
  {
    id: 3,
    name: 'Slaapkamer',
    speech: 'Slaapkamer',
    src: './images/slaapkamer.jpg',
    parentId: 2,
    childrenIds: null,
  },
  {
    id: 4,
    name: 'Tuin',
    speech: 'Tuin',
    src: './images/natuur.webp',
    parentId: 0,
    childrenIds: [401, 402, 403],
  },
  {
    id: 5,
    name: 'Ontbijt & lunch',
    speech: 'Ontbijt en lunch',
    src: './images/ontbijt_en_lunch.jpg',
    parentId: 0,
    childrenIds: [13, 14],
    linkIds: [11],
  },
  {
    id: 6,
    name: 'Keerkring',
    speech: 'Keerkring in Blauwborgje',
    src: './images/blauwborgje.jpg',
    parentId: 0,
    childrenIds: [601, 602, 603, 604, 605],
  },
  {
    id: 7,
    name: 'Uitstapjes',
    speech: 'Uitstapjes',
    src: './images/blauwborgje.jpg',
    parentId: 0,
    childrenIds: [4],
    //linkIds: []
  },
  {
    id: 8,
    name: 'Avondeten',
    speech: 'Avondeten',
    src: './images/avondeten.webp',
    parentId: 0,
    childrenIds: [16],
    //linkIds: []
  },
  {
    id: 9,
    name: 'Lekkere dingen',
    speech: 'Lekkere dingen',
    src: './images/lekkere_dingen.jpg',
    parentId: 0,
    childrenIds: [901, 902, 903, 904, 16],
    //linkIds: []
  },
  {
    id: 10,
    name: 'Bestek',
    speech: 'Bestek',
    src: './images/bestek.jpg',
    parentId: 2,
    childrenIds: [1001, 1002, 1003, 1004],
    linkIds: [5],
  },
  {
    id: 11,
    name: 'Servies',
    speech: 'Servies',
    src: './images/servies.jpg',
    parentId: 2,
    childrenIds: [1101, 1102, 1103],
    linkIds: [2, 12],
  },
  {
    id: 12,
    name: 'Pannen',
    speech: 'Pannen',
    src: './images/pannen.png',
    parentId: 2,
    childrenIds: [1201, 1202, 1203],
    linkIds: [2],
  },
  {
    id: 13,
    name: 'Brood',
    speech: 'Brood',
    src: './images/brood.jpg',
    parentId: 2,
    childrenIds: [1301, 1302, 1303, 1304, 1305, 1306],
    linkIds: [14],
  },
  {
    id: 14,
    name: 'Beleg',
    speech: 'Beleg',
    src: './images/broodbeleg.jpg',
    parentId: 2,
    childrenIds: [1401, 1402, 1403],
    linkIds: [13],
  },
  {
    id: 15,
    name: 'Meubels',
    speech: 'Meubels',
    src: './images/woonkamer.jpg',
    parentId: 2,
    childrenIds: [1501, 1502, 1503],
    //linkIds: []
  },
  {
    id: 16,
    name: 'Snacks',
    speech: 'Snacks',
    src: './images/snacks_2.jpg',
    parentId: 2,
    childrenIds: [1601, 1602, 1603, 1604],
    //linkIds: []
  },
  {
    id: 50,
    name: 'Huis',
    speech: 'Huis',
    src: './images/huis.jpg',
    parentId: 0,
    childrenIds: [1, 2, 3],
    //linkIds: [],
  },
  // Tuin
  {
    id: 401,
    name: 'Boom',
    speech: 'Booom',
    src: './images/boom.jpg',
    parentId: 4,
    childrenIds: null,
  },
  {
    id: 402,
    name: 'Berg',
    speech: 'Berg',
    src: './images/berg.jpg',
    parentId: 4,
    childrenIds: null,
  },
  {
    id: 403,
    name: 'Meer',
    speech: 'Meer',
    src: './images/meer.jpg',
    parentId: 4,
    childrenIds: null,
  },
  // Keerkring
  {
    id: 601,
    name: 'Blauwbörgje',
    speech: 'De Keerkring in Blauwbörgje',
    src: './images/blauwborgje.jpg',
    parentId: 6,
    childrenIds: null,
  },
  {
    id: 602,
    name: 'Taxibusje',
    speech: 'Taxibusje Dorenbos',
    src: './images/taxi_busje_dorenbos.jpg',
    parentId: 6,
    childrenIds: null,
  },
  {
    id: 603,
    name: 'Bewegen op muziek',
    speech: 'Bewegen op muziek',
    src: './images/bewegen_voor_ouderen.png',
    parentId: 6,
    childrenIds: null,
  },
  {
    id: 604,
    name: 'Sjoelbak',
    speech: 'Sjoelbak',
    src: './images/sjoelen.jpg',
    parentId: 6,
    childrenIds: null,
  },
  {
    id: 605,
    name: 'Duofiets',
    speech: 'Duofiets',
    src: './images/duofiets.jpg',
    parentId: 6,
    childrenIds: null,
  },
  // Lekkere dingen
  {
    id: 901,
    name: 'Appeltaart',
    speech: 'Appeltaart',
    src: './images/appeltaart.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 902,
    name: 'Koffiebroodje',
    speech: 'Koffiebroodje',
    src: './images/koffiebroodje.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 903,
    name: 'Slagroomtaart',
    speech: 'Slagroomtaart',
    src: './images/slagroomtaart.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 904,
    name: 'Vlaai',
    speech: 'Vlaai',
    src: './images/vlaai_assorti.png',
    parentId: 9,
    childrenIds: null,
  },
  // Bestek
  {
    id: 1001,
    name: 'Mes',
    speech: 'Mes',
    src: './images/mes.jpg',
    parentId: 10,
    childrenIds: null,
  },
  {
    id: 1002,
    name: 'Vork',
    speech: 'Vork',
    src: './images/vork.jpg',
    parentId: 10,
    childrenIds: null,
  },
  {
    id: 1003,
    name: 'Lepel',
    speech: 'Lepel',
    src: './images/lepel.jpg',
    parentId: 10,
    childrenIds: null,
  },
  {
    id: 1004,
    name: 'Theelepeltje',
    speech: 'Theelepeltje',
    src: './images/theelepel.jpg',
    parentId: 10,
    childrenIds: null,
  },
  // Servies
  {
    id: 1101,
    name: 'Bord',
    speech: 'Bord',
    src: './images/bord.jpg',
    parentId: 11,
    childrenIds: null,
  },
  {
    id: 1102,
    name: 'Beker',
    speech: 'Beker',
    src: './images/beker.jpg',
    parentId: 11,
    childrenIds: null,
  },
  {
    id: 1102,
    name: 'Kopje',
    speech: 'Kopje',
    src: './images/kopje.jpg',
    parentId: 11,
    childrenIds: null,
  },
  {
    id: 1103,
    name: 'Theeglas',
    speech: 'Theeglas',
    src: './images/theeglas.jpg',
    parentId: 11,
    childrenIds: null,
  },
  {
    id: 1104,
    name: 'Bord',
    speech: 'Bord',
    src: './images/bord.jpg',
    parentId: 11,
    childrenIds: null,
  },
  // Pannen
  {
    id: 1201,
    name: 'Pan',
    speech: 'Pan',
    src: './images/pan.jpg',
    parentId: 12,
    childrenIds: null,
    //linkIds: []
  },
  {
    id: 1202,
    name: 'Koekenpan',
    speech: 'Koekenpan',
    src: './images/koekenpan.webp',
    parentId: 12,
    childrenIds: null,
    //linkIds: []
  },

  // Brood
  {
    id: 1301,
    name: 'Bruin brood',
    speech: 'Plakje bruin brood',
    src: './images/bruin_brood.jpg',
    parentId: 13,
    childrenIds: null,
  },
  {
    id: 1302,
    name: 'Wit brood',
    speech: 'Plakje wit brood',
    src: './images/wit_brood.jpg',
    parentId: 13,
    childrenIds: null,
  },
  {
    id: 1303,
    name: 'Krentenbrood',
    speech: 'Plakje krentenbrood',
    src: './images/rozijnenbrood.jpg',
    parentId: 13,
    childrenIds: null,
  },
  {
    id: 1304,
    name: 'Krentenbol',
    speech: 'Krentenbol',
    src: './images/krentenbol.jpg',
    parentId: 13,
    childrenIds: null,
  },
  {
    id: 1305,
    name: 'Roggebrood',
    speech: 'Plakje roggebrood',
    src: './images/roggebrood.jpg',
    parentId: 13,
    childrenIds: null,
  },
  {
    id: 1305,
    name: 'Beschuit',
    speech: 'Beschuitje',
    src: './images/beschuitje.jpg',
    parentId: 13,
    childrenIds: null,
  },
  // Beleg
  {
    id: 1401,
    name: 'Hagelslag',
    speech: 'Hagelslag',
    src: './images/hagelslag_puur_ah.jpg',
    parentId: 14,
    childrenIds: null,
  },
  {
    id: 1402,
    name: 'Honing',
    speech: 'Honing',
    src: './images/honing.jpg',
    parentId: 14,
    childrenIds: null,
  },
  {
    id: 1403,
    name: 'Boter',
    speech: 'Boter',
    src: './images/margarine.jpg',
    parentId: 14,
    childrenIds: null,
  },
  // Meubels
  {
    id: 1501,
    name: 'tafel',
    speech: 'Tafel',
    src: './images/tafel.jpg',
    parentId: 15,
    childrenIds: null,
  },
  {
    id: 1502,
    name: 'stoel',
    speech: 'Stoel',
    src: './images/stoel.jpg',
    parentId: 15,
    childrenIds: null,
  },
  {
    id: 1503,
    name: 'kast',
    speech: 'Kast',
    src: './images/kast.jpg',
    parentId: 15,
    childrenIds: null,
  },
  {
    id: 1504,
    name: 'bank',
    speech: 'Bank',
    src: './images/bank.png',
    parentId: 15,
    childrenIds: null,
  },
  // Snacks
  {
    id: 1601,
    name: 'Friet',
    speech: 'Friet',
    src: './images/patat_friet.jpg',
    parentId: 16,
    childrenIds: null,
  },
  {
    id: 1602,
    name: 'Kroket',
    speech: 'Kroket',
    src: './images/kroket.jpg',
    parentId: 16,
    childrenIds: null,
  },
  {
    id: 1603,
    name: 'Kaassoufle',
    speech: 'Kaassoufle',
    src: './images/kaassoufle.jpg',
    parentId: 16,
    childrenIds: null,
  },
  {
    id: 1604,
    name: 'Frikandel',
    speech: 'Frikandel',
    src: './images/frikandel.jpeg',
    parentId: 16,
    childrenIds: null,
  },
];
