import { Card } from '../interfaces/card';

export const CardsData: Card[] = [
  {
    id: 0,
    name: 'hoofdcategorieën',
    speech: 'hoofdcategorieën',
    src: '',
    parentId: null,
    childrenIds: [1, 5, 14],
  },
  {
    id: 1,
    name: 'alledaagse dingen',
    speech: 'Alle daagse dingen',
    src: './images/dingen.jpg',
    parentId: 0,
    childrenIds: [2, 5],
  },
  {
    id: 2,
    name: 'huis',
    speech: 'Huis',
    src: './images/huis.jpg',
    parentId: 1,
    childrenIds: [3, 4],
    linkIds: [9],
  },
  {
    id: 3,
    name: 'keuken',
    speech: 'Keuken',
    src: './images/keuken.jpg',
    parentId: 2,
    childrenIds: [21, 22],
    linkIds: [22],
  },
  {
    id: 4,
    name: 'woonkamer',
    speech: 'Woonkamer',
    src: './images/woonkamer.jpg',
    parentId: 2,
    childrenIds: [10, 11, 12, 13],
    // linkIds: [9],
  },
  {
    id: 5,
    name: 'natuur',
    speech: 'Natuur',
    src: './images/natuur.webp',
    parentId: 0,
    childrenIds: [6, 7, 8],
  },
  {
    id: 6,
    name: 'boom',
    speech: 'Booom',
    src: './images/boom.jpg',
    parentId: 5,
    childrenIds: null,
  },
  {
    id: 7,
    name: 'berg',
    speech: 'Berg',
    src: './images/berg.jpg',
    parentId: 5,
    childrenIds: null,
  },
  {
    id: 8,
    name: 'meer',
    speech: 'Meer',
    src: './images/meer.jpg',
    parentId: 5,
    childrenIds: null,
  },
  {
    id: 9,
    name: 'meubels',
    speech: 'Meubels',
    src: './images/meer.jpg',
    parentId: 9,
    childrenIds: [10, 11, 12, 13],
  },
  {
    id: 10,
    name: 'tafel',
    speech: 'Tafel',
    src: './images/tafel.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 11,
    name: 'stoel',
    speech: 'Stoel',
    src: './images/stoel.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 12,
    name: 'kast',
    speech: 'Kast',
    src: './images/kast.jpg',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 13,
    name: 'bank',
    speech: 'Bank',
    src: './images/bank.png',
    parentId: 9,
    childrenIds: null,
  },
  {
    id: 14,
    name: 'Ontbijt & lunch',
    speech: 'Ontbijt en lunch',
    src: './images/ontbijt_en_lunch.jpg',
    parentId: 0,
    childrenIds: [15, 16, 17],
    linkIds: [3, 18],
  },
  {
    id: 15,
    name: 'Bruin brood',
    speech: 'Plakje bruin brood',
    src: './images/bruin_brood.png',
    parentId: 14,
    childrenIds: null,
  },
  {
    id: 16,
    name: 'Wit brood',
    speech: 'Plakje wit brood',
    src: './images/wit_brood.png',
    parentId: 14,
    childrenIds: null,
  },
  {
    id: 17,
    name: 'Krentenbrood',
    speech: 'Plakje krentenbrood',
    src: './images/krentenbrood.png',
    parentId: 14,
    childrenIds: null,
  },
  {
    id: 18,
    name: 'Bestek',
    speech: 'Bestek',
    src: './images/bestek.jpg',
    parentId: 14,
    childrenIds: [19, 20],
  },
  {
    id: 19,
    name: 'Mes',
    speech: 'Mes',
    src: './images/mes.jpg',
    parentId: 18,
    childrenIds: null,
  },
  {
    id: 20,
    name: 'Vork',
    speech: 'Vork',
    src: './images/vork.png',
    parentId: 18,
    childrenIds: null,
  },
  {
    id: 21,
    name: 'Kookplaat',
    speech: 'Kookplaat',
    src: './images/kookplaat.png',
    parentId: 3,
    childrenIds: null,
  },
  {
    id: 22,
    name: 'Pannen',
    speech: 'Pannen',
    src: './images/pannen.png',
    parentId: 3,
    childrenIds: null,
  },
];
